# Generated by Django 3.2.1 on 2021-06-22 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=10)),
                ('experience', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=1)),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=300)),
                ('contact', models.CharField(max_length=10)),
                ('profile_pic', models.ImageField(null=True, upload_to='aaa')),
                ('activation_code', models.CharField(max_length=100, null=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.city')),
                ('status', models.ForeignKey(default=2, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.status')),
            ],
            options={
                'db_table': 'teachers',
            },
        ),
    ]
