# Generated by Django 3.2.1 on 2021-06-30 13:30

from django.db import migrations, models
import teachers.models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_auto_20210625_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to=teachers.models.Teacher.getPicPath),
        ),
    ]
