# Generated by Django 3.2.1 on 2021-06-12 12:47

from django.db import migrations, models
import django.db.models.deletion
import institutes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('contact', models.CharField(max_length=10)),
                ('activation_code', models.CharField(max_length=20, null=True)),
                ('details', models.CharField(max_length=2000, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('start_date', models.DateField(null=True)),
                ('logo', models.ImageField(null=True, upload_to=institutes.models.Institute.get_upload_path)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.city')),
                ('status', models.ForeignKey(default=2, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.status')),
            ],
            options={
                'db_table': 'institutes',
            },
        ),
        migrations.CreateModel(
            name='PicType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic_type', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'pic_types',
            },
        ),
        migrations.CreateModel(
            name='InstitutePic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic_path', models.ImageField(upload_to=institutes.models.InstitutePic.get_upload_path)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutes.institute')),
                ('pictype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='institutes.pictype')),
            ],
            options={
                'db_table': 'institute_pics',
            },
        ),
    ]
