# Generated by Django 3.2.1 on 2021-06-15 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('subtitle', models.CharField(max_length=80)),
                ('details', models.CharField(max_length=2000)),
                ('syllabus', models.FileField(null=True, upload_to='golu')),
                ('course_pic', models.ImageField(null=True, upload_to='bholu')),
                ('star_rank', models.IntegerField(null=True)),
                ('star_rank_count', models.IntegerField(null=True)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutes.institute')),
            ],
            options={
                'db_table': 'courses',
            },
        ),
    ]
