# Generated by Django 3.2.1 on 2021-06-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0002_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='star_rank',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='star_rank_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
